"""
ott_producer.py
---------------
Reads ott_viewer_events.csv generated by generate_data.py and streams each
row as a JSON message to the Kafka topic "viewer-events".

Expected CSV columns from generate_data.py:
event_id, user_id, content_id, content_title, content_type, device,
event_type, watch_duration_sec, total_duration_sec, region, timestamp

Usage:
    python ott_producer.py
    python ott_producer.py --csv path/to/ott_viewer_events.csv
    python ott_producer.py --broker localhost:9092 --delay-min 0.1 --delay-max 0.5
    python ott_producer.py --loop
"""

import argparse
import csv
import json
import random
import time
from datetime import datetime
from pathlib import Path

TOPIC_NAME = "viewer-events"

# Check common locations because generate_data.py writes CSV files to the
# current working directory, while some project layouts store them in /data.
SCRIPT_DIR = Path(__file__).resolve().parent
CSV_CANDIDATES = [
    SCRIPT_DIR / "ott_viewer_events.csv",
    SCRIPT_DIR / "data" / "ott_viewer_events.csv",
    SCRIPT_DIR.parent / "data" / "ott_viewer_events.csv",
    Path.cwd() / "ott_viewer_events.csv",
    Path.cwd() / "data" / "ott_viewer_events.csv",
]

REQUIRED_COLUMNS = {
    "event_id", "user_id", "content_id", "content_title", "content_type",
    "device", "event_type", "watch_duration_sec", "total_duration_sec",
    "region", "timestamp",
}


def find_default_csv() -> Path:
    for candidate in CSV_CANDIDATES:
        if candidate.is_file():
            return candidate
    # Return the most likely project data path so the error can name it clearly.
    return SCRIPT_DIR.parent / "data" / "ott_viewer_events.csv"


def build_producer(broker: str):
    try:
        from kafka import KafkaProducer
        from kafka.errors import NoBrokersAvailable
    except (ImportError, ModuleNotFoundError) as exc:
        raise RuntimeError(
            "Kafka Python library could not be imported. In your active virtual "
            "environment, run:\n"
            "python -m pip uninstall kafka kafka-python -y\n"
            "python -m pip install --no-cache-dir kafka-python==2.2.15"
        ) from exc

    try:
        return KafkaProducer(
            bootstrap_servers=broker,
            value_serializer=lambda value: json.dumps(value).encode("utf-8"),
            key_serializer=lambda key: key.encode("utf-8") if key else None,
            linger_ms=10,
        )
    except NoBrokersAvailable as exc:
        raise ConnectionError(
            f"Could not connect to Kafka broker at {broker}. "
            "Check that Kafka is running and the broker address is correct."
        ) from exc


def load_events(csv_path: Path):
    if not csv_path.is_file():
        candidates = "\n".join(f"  - {path}" for path in CSV_CANDIDATES)
        raise FileNotFoundError(
            f"CSV file not found: {csv_path}\n"
            "Run generate_data.py first, or provide the path with --csv.\n"
            f"Default locations checked:\n{candidates}"
        )

    with csv_path.open("r", newline="", encoding="utf-8-sig") as file:
        reader = csv.DictReader(file)
        actual_columns = set(reader.fieldnames or [])
        missing_columns = REQUIRED_COLUMNS - actual_columns
        if missing_columns:
            raise ValueError(
                f"CSV schema does not match generate_data.py. Missing columns: "
                f"{', '.join(sorted(missing_columns))}. "
                f"Found columns: {', '.join(reader.fieldnames or [])}"
            )
        rows = list(reader)

    if not rows:
        raise ValueError(f"CSV file contains no event rows: {csv_path}")
    return rows


def stream_events(
    csv_path: Path,
    broker: str,
    delay_min: float,
    delay_max: float,
    loop: bool,
):
    if delay_min < 0 or delay_max < 0 or delay_min > delay_max:
        print("ERROR: Delays must be non-negative and delay-min must be <= delay-max.")
        return

    try:
        rows = load_events(csv_path)
    except (FileNotFoundError, ValueError, OSError) as exc:
        print(f"ERROR: {exc}")
        return

    try:
        producer = build_producer(broker)
    except (RuntimeError, ConnectionError) as exc:
        print(f"ERROR: {exc}")
        return

    print(
        f"Loaded {len(rows)} events from '{csv_path}'. "
        f"Streaming to Kafka topic '{TOPIC_NAME}' at {broker}... "
        "(Ctrl+C to stop)\n"
    )

    sent_count = 0
    try:
        while True:
            for row in rows:
                # Preserve the generated dataset fields and add the send time.
                message = dict(row)
                message["sent_at"] = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

                future = producer.send(
                    TOPIC_NAME,
                    key=message["content_id"],
                    value=message,
                )
                metadata = future.get(timeout=10)

                sent_count += 1
                print(
                    f"[{sent_count}] sent -> topic={metadata.topic} "
                    f"partition={metadata.partition} offset={metadata.offset} "
                    f"| {message['event_type']} | user={message['user_id']} "
                    f"| content='{message['content_title']}'"
                )
                time.sleep(random.uniform(delay_min, delay_max))

            if not loop:
                break
            print("\n-- reached end of dataset, looping back to start --\n")
    except KeyboardInterrupt:
        print("\nStopped by user.")
    except Exception as exc:
        print(f"\nERROR while sending events: {exc}")
    finally:
        producer.flush()
        producer.close()
        print(f"\nDone. Total messages sent: {sent_count}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Stream OTT viewer events generated by generate_data.py to Kafka."
    )
    parser.add_argument(
        "--broker", default="localhost:9092",
        help="Kafka bootstrap server (default: localhost:9092)",
    )
    parser.add_argument(
        "--csv", default=str(find_default_csv()),
        help="Path to ott_viewer_events.csv generated by generate_data.py",
    )
    parser.add_argument(
        "--delay-min", type=float, default=0.1,
        help="Minimum seconds between messages (default: 0.1)",
    )
    parser.add_argument(
        "--delay-max", type=float, default=0.4,
        help="Maximum seconds between messages (default: 0.4)",
    )
    parser.add_argument(
        "--loop", action="store_true",
        help="Keep cycling through the CSV after reaching the end",
    )
    args = parser.parse_args()

    stream_events(
        Path(args.csv),
        args.broker,
        args.delay_min,
        args.delay_max,
        args.loop,
    )
